[metadata]
package = "github.com/crazy-max/nodejs-portable"
homepage = "https://github.com/crazy-max/nodejs-portable"
license = "MIT"

[[constraint]]
  name = "github.com/cavaliercoder/grab"
  version = "~1.0.0"

[[constraint]]
  name = "github.com/fatih/color"
  version = "~1.4.1"

[[constraint]]
  name = "github.com/mcuadros/go-version"

[[constraint]]
  name = "github.com/op/go-logging"
